# -*- coding: utf-8 -*-
"""My_Colabratory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11_l4VQ80EuzN2rNuO0bCCMU7r9mjHvgU
"""

!pip install -Uqq fastbook
import fastbook
from fastbook import *

from fastai.vision.all import *
#0 
dest = '/content/DataML'
path = untar_data (URLs.PETS, data=dest)/'images' 
list(path.ls())
#1  label_func
def is_cat(x):  # Cat Labels = 1 or True
  return x[0].isupper() 
#2 item_tfms
### doc(ImageDataLoaders.from_name_func)  ???
dls = ImageDataLoaders.from_name_func(
    path=path, fnames=get_image_files(path),        
    valid_pct=0.2, seed=42, # testing set 
    bs =64, # Batch size
    label_func=is_cat, item_tfms=Resize(224)
)
## Overfitting 
## Optimum
## Underfitting

## Training set 
## Validation set (testing set)

learn = cnn_learner(dls, # use data_lodear dls
                    resnet34, # CNN Architecters res net 34 Layers 
                    metrics=error_rate)  # model Performance with claculation error_rate
learn.summary() # show CNN Model schema 
# checking the Total_traingable_params ?
learn.fine_tune(1) # Training set with (fine_tune())

learn.summary() # show CNN Model schema 
# checking the Total_traingable_params = 21,813,056

uploader = widgets.FileUpload()
uploader

img = PILImage.create(uploader.data[0])
pred,_,_ = learn.predict(img)
if pred == 'True': 
    print(f'Prediction: Cat')
else: 
    print(f'Prediction: Dog')

learn.show_results()

doc(ImageDataLoaders.from_name_func)